### ISSUE TITLE
"styling" of login dialog

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-basicauth#5]
We could add a little "inline" css styles for the login dialog.

+ include logo
+ full width
+ luya colors?

**Comment by TheMaaarc** [comment]
![screen shot 2018-12-19 at 14 49 08](https://user-images.githubusercontent.com/3450438/50225735-a0913680-03a1-11e9-98e1-b24736075901.png)
![screen shot 2018-12-19 at 14 49 13](https://user-images.githubusercontent.com/3450438/50225736-a0913680-03a1-11e9-9888-403e0ab17327.png)
